### PR TITLE
PHP UI for JSON Traits

### PR DESCRIPTION
**Pull request by ghost**
Initial UI in place where users can manually add in the trait information into a web form, instead of editing JSON directly.

Features to be implemented before merge:

* [x] Clean up aesthetics
* [x] Update README
* [x] Simple instructions in the UI
* [x] Generate `config.json`
* [x] Convert RGB inputs to a color picker
* [x] Convert filename fields to file browsers

We'll create other pull requests for future features here, like running the whole process from the UI.

### CODE REVIEW

**Comment by sk33z3r** [comment]
@Montspy 

**Note about directories:**

I got rid of the example `collection_name` folder since the UI will handle this, and moved `images` to `collections`. I think it is more fitting to how things are structured now.

**Notes about the JSON traits output:**

* The `artist_address` is optional. If the user doesn't input it, then I don't add it.
* `background_color` is a bit misleading. It's a flipped boolean, so `0` actually means `YES` in this case. Basically the front end is telling the backend "If the user wants a background color, start at `layer00`. If not, start at `layer01`.
* `traits` and `variations` are purely for my front-end and may not serve any purpose in python.
* I run the rarity in a simple way:

| Rarity | Value |
|---|---|
| Legendary | 1 |
| Rare | 2 |
| Uncommon | 3 |
| Common | 4 |

I _think_ this will work properly, but perhaps we need to adjust those values.

**Comment by sk33z3r** [comment]
Couple other notes:

* I put the `minter_address` in the collection `traits.json` instead of a main `config.json`, because I think there will be cases where the minter/artist does not match up. It would likely be on a per collection basis, so it made sense add this in here.
* `artist_name` and `artist_address` are intended to be added to metadata files as their own fields.

**Comment by sk33z3r** [comment]
@Montspy I moved the mint address back to config. I kept thinking about it, and I think that maybe can stay in config since it's related to minting specifically.

If we desire, we can always pull the address from the config and place into the metadata on generation.

Otherwise, I changed up endpoints a little to get setup for new features:

* `localhost:8080/` - is now a generic home menu
* `localhost:8080/setup` - puts you at STEP 01 for setting up image generation
* `localhost:8080/config` - puts you at STEP 01 for config setup

The page exists, but editing mechanism isn't there yet, for these:

* `localhost:8080/setup/edit`
* `localhost:8080/config/edit`

**Comment by sk33z3r** [comment]
@Montspy finally remembered to put `collection_lower` in the json...

**Comment by sk33z3r** [comment]
@Montspy this PR is ready when you have your side sorted and confirm there are no more changes needed in PHP. I opened other tickets since I think it is in a good enough place for testers.

Before we attempt to merge, should we review and merge in #30 first?

**Comment by Montspy** [comment]
@sk33z3r I think we should merge this before #30 simply because we've both tested this branch more than #30.
In terms of merge conflicts, I don't see a big difference in the merge order between this branch and #30.

I released a new version of LooPyMinty for this branch, make sure to update your submodules! 
This new release adds:
+ resolve ENS, account IDs and ETH addresses for `minter` and `royalty_address`
+ loads the current `traits.json` and `config.json`

**Review by Montspy — APPROVED** [review]

**Pull request merged**
