### PR TITLE
WIP: Quality of life Updates

### PR DESCRIPTION
**Pull request by ghost**
TODO:

- [x] Cleanup UI forms
- [x] Implement single CID mint
- [x] Python adjustments + PHP implementation
- [x] Tweak rarity inputs
- [x] JWT implementation
- [x] Composer for PHP plugins
- [x] Companion app

Things to prepare for on the Wiki:

- [x] Update procedure
- [x] Release Notes
- [x] Update guides with new screenshots

Nice-to-have:

- [x] Traits editor
- [x] Transfer tools

### CODE REVIEW

**Comment by sk33z3r** [comment]
Still a few things to do, but initially everything built properly so that's a good first step.

**Comment by sk33z3r** [comment]
[Create a branch in LoopMinterJS that only includes the dashboard repo](https://trello.com/c/3BMjaden/19-create-a-branch-in-loopminterjs-that-only-includes-the-dashboard-repo)

**Comment by sk33z3r** [comment]
[React Dashboard integration to LooPyGen](https://trello.com/c/5mo793lA/18-react-dashboard-integration-to-loopygen)

**Comment by sk33z3r** [comment]
@you3h Got the new submodule in place, however I can't seem to load the UI.

When using the proxy:
image

When hitting the react container directly:
image

I get no log output from the container:

```shell
~/g/loopygen (dev/react-ui)> docker-compose logs react
Attaching to loopygen.react
loopygen.react | > loopminterjs-api@1.0.0 start
loopygen.react | > node index.js
loopygen.react | 2022-04-22T16:08:57.704Z: [info] [LOOPMINTER_API] version 1.0.0 starting
loopygen.react | 2022-04-22T16:08:57.707Z: [info] [NFT SERVICE] started
loopygen.react | 2022-04-22T16:08:57.707Z: [info] [Image SERVICE] started
loopygen.react | 2022-04-22T16:08:57.710Z: [info] [LOOPMINTER_API] started, listening at port 8000
```

Browser Console:
image

**Comment by sk33z3r** [comment]
Issue above is resolved, new list that block merge:
https://github.com/you3h/LooPyGen_Client/issues

**Comment by Montspy** [comment]
A couple of notes regarding the React UI:

Overall feedback:
* Limit content to the center ~1000px
* Expanded navigation bar by default (with titles: "Minting config", "Collection wizard", ...)

Collection Wizard:
* More contrast on buttons ("+ Add background", "+ Add Variation")
* Pre-populate Rarity Uncommon
* Should it create the source_layers folder too?

Minting config:
* What is alias?
* No need for minterId
* "User address" should be "Minter address"
* No need for apiKey
* Private key should be required
Keep getting "Something went wrong while updating user"

**Comment by Montspy** [comment]
https://github.com/you3h/LooPyGen_Client/issues/20 Should be addressed before merge

**Comment by sk33z3r** [comment]
Reverting back to PHP and implementing some of the basics we talked about before React

**Comment by sk33z3r** [comment]
[LooPyGen v1.0.0 Release](https://trello.com/c/xiXUgvEa/41-loopygen-v100-release)

**Comment by Montspy** [comment]
Traits editor alpha in 9217c3f

**Comment by sk33z3r** [comment]
Ran a new user through  setup using a manually pushed image. The Wiki for v1 is updated with the bare minimum setup process without a companion app.

Other than https://github.com/sk33z3r/LooPyGen/pull/47/commits/18587f12d4c180efb5a8cc099c4e861c123fdf99 and needing to enable Virtualization in BIOS, there were no issues or any confusion in how to use the app.

https://wiki.ezl2.app/en/v1

**Pull request merged**
